### ISSUE TITLE
Allow option to show 'emoji and symbols' and show 'keyboard viewer'

### ISSUE THREAD

**Issue by mostinho7** [freefelt/YouType#8]
Thanks for the effort creating this. I would like to use it as my main keyboard indicator and hide the system one. However, the system menu has additional options such as showing the 'keyboard viewer ' which presents an onscreen virtual keyboard for typing languages that use non-english letters (such as Arabic, Russian, Hebrew etc). Whenever I am typing in one of these languages, I always present the onscreen keyboard so I can know which keys on the keyboard correspond to which letters in the language.
What I am requesting is that your application 'YouType' also have an option in the dropdown to show the keyboard viewer and the emoji viewer.

Thanks!

<img width="217" alt="image" src="https://user-images.githubusercontent.com/8954565/174485354-bee534ec-d9b8-46d1-a57a-a9d963d8edc0.png">

<img width="669" alt="image" src="https://user-images.githubusercontent.com/8954565/174485532-1bede1e1-e551-4d31-b31a-8442a33bd758.png">

**Comment by freefelt** [comment]
Hi! Thanks for the feedback. The options will be in the next release.
But there is no good way to show the on-screen keyboard in the latest versions of mac OS, as it turned out. So I had to do it with a script that opens the settings and puts the appropriate check mark. Unfortunately, this requires another permit for Automation.
![Screenshot1](https://user-images.githubusercontent.com/9737848/176435640-1fc901eb-9291-409e-8c49-251241516ddf.png)

Also, you can use a shortcut Option (⌥), Command (⌘), and F5 (on some computers, you might need to press the Fn (Function) key as well) and turn the the on-screen keyboard from there.
![Screenshot2](https://user-images.githubusercontent.com/9737848/176435962-da59eae4-d53c-44c2-b01f-ae6e862f9148.png)

**Comment by freefelt** [comment]
Implemented in YouType 0.7
